=== LeaneTEXIER/Master_1/S2/LABD/labd-1/Exercice4.dtd
<!ELEMENT transpole (depart, arrivee, date, modes, preference, vitesseMarche, tempsParcours, itineraire)>
<!ELEMENT depart (#PCDATA)>
<!ELEMENT arrivee (#PCDATA)>
<!ELEMENT date (jour, horaire)>
<!ELEMENT jour (#PCDATA)>
<!ELEMENT horaire (#PCDATA)>
<!ELEMENT modes (mode*)>
<!ELEMENT mode (#PCDATA)>
<!ELEMENT preference (#PCDATA)>
<!ELEMENT vitesseMarche (#PCDATA)>
<!ELEMENT tempsParcours (heure, minutes)>
<!ELEMENT heure (#PCDATA)>
<!ELEMENT minutes (#PCDATA)>
<!ELEMENT itineraire (etape+)>
<!ELEMENT etape (ligne?, duree, arretFin)>
<!ATTLIST etape horaire CDATA #IMPLIED
		     mode CDATA #REQUIRED
		     compagnie CDATA #IMPLIED>
<!ELEMENT ligne (#PCDATA)>
<!ATTLIST ligne direction CDATA #REQUIRED>
<!ELEMENT duree (#PCDATA)>
<!ATTLIST duree unite CDATA #REQUIRED>
<!ELEMENT arretFin (#PCDATA)>

=== LeaneTEXIER/Master_1/S2/LABD/labd-1/Exercice4.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE transpole SYSTEM "Exercice4.dtd">
<transpole>
	<depart>Seclin - Centre hospitalier</depart>
	<arrivee>Roubaix - Avenue Motte</arrivee>
	<date>
		<jour>Mardi 22 janvier</jour>
		<horaire>12h35</horaire>
	</date>
	<modes>
		<mode>Métro</mode>
		<mode>Tramway</mode>
		<mode>Bus</mode>
		<mode>Car</mode>
	</modes>
	<preference>Arriver le plus rapidement</preference>
	<vitesseMarche>Normale</vitesseMarche>
	<tempsParcours>
		<heure>1</heure>
		<minutes>27</minutes>
	</tempsParcours>
	<itineraire>
		<etape mode="Marche">
			<duree unite="min">13</duree>
			<arretFin>Seclin - Hôtel de Ville</arretFin>
		</etape>
		<etape horaire="14h51" mode="Bus" compagnie="TRANSPOLE">
			<ligne direction="Lille - Porte des Postes">52</ligne>
			<duree unite="min">23</duree>
			<arretFin>Lille - CHR B Calmette</arretFin>
		</etape>
		<etape horaire="15h18" mode="Métro" compagnie="TRANSPOLE">
			<ligne direction="Villeneuve d’Ascq - 4 Cantons Grand Stade">1</ligne>
			<duree unite="min">3</duree>
			<arretFin>Lille - Porte des Postes</arretFin>
		</etape>
		<etape horaire="15h27" mode="Métro" compagnie="TRANSPOLE">
			<ligne direction="Tourcoing - CH Dron">2</ligne>
			<duree unite="min">25</duree>
			<arretFin>Roubaix - Epeule Montesquieu</arretFin>
		</etape>
		<etape horaire="15h56" mode="Bus" compagnie="TRANSPOLE">
			<ligne direction="Roubaix - fraternité">25</ligne>
			<duree unite="min">9</duree>
			<arretFin>Roubaix - Avenue Motte</arretFin>
		</etape>
	</itineraire>
</transpole>
